name: GitHub Matrix Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        services:
          - name: backend
            image: python:3.10-slim
            ecr_repo: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/april-ecs-3tier-backend
            path: day13-ecs-3-tier/app/backend
          - name: frontend
            image: node:14-alpine
            ecr_repo: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/april-ecs-3tier-frontend
            path: day13-ecs-3-tier/app/frontend

          - name: ms1

          - name: ms2
  


    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: build ${{ matrix.services.name }}
        run: |
          cd ${{ matrix.services.path }}
          docker build -t ${{ matrix.services.ecr_repo }}:${{ github.sha }} .
          docker build -t ${{ matrix.services.ecr_repo }}:latest .
          docker push ${{ matrix.services.ecr_repo }}:${{ github.sha }}
          docker push ${{ matrix.services.ecr_repo }}:latest
